title: Your Jekyll Site
description: A description of your site

theme: minima # or use your preferred Jekyll theme

# Add any other Jekyll configuration settings you need

# Custom styles
style: |
  body {
    margin: 0;
    overflow: hidden;
  }

  .parallax-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    overflow: hidden;
  }

  .parallax-bg {
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: linear-gradient(to bottom right, #3498db, #ffffff);
    transform: translate(100%, 100%);
  }
